Repository stolostron/search-operator, pull requests merged in 2021-06, with the labels that each got.

#62 Set user 1001 (non root) in Docker image
  Dockerfile
Labels: approved, lgtm

#63 [release-2.2] Set user 1001 (non root) in Docker image
  Dockerfile
Labels: lgtm

#64 Remove duplicate imports - cleanup
  controllers/searchoperator_controller.go
Labels: approved, lgtm

#66 Add labels to redisgraph statefulset to fix cert renewal issue
  controllers/searchoperator_controller.go
Labels: approved, lgtm

#65 [2.2] Add labels to redisgraph statefulset to fix cert renewal issue
  controllers/searchoperator_controller.go
  go.mod
  go.sum
Labels: do-not-merge/hold, lgtm

#67 update search operator status in case of error
  cicd-scripts/run-e2e-tests.sh
  controllers/searchoperator_controller.go
Labels: approved, lgtm
