Repository stolostron/search-operator, pull requests merged in 2021-04, with the labels that each got.

#52 dummy update for base image rebuild
  README.md
  build/Dockerfile
  go.sum
Labels: approved, lgtm

#55 Removed ca.crt
  controllers/searchoperator_controller.go
Labels: approved, do-not-merge/hold, lgtm

#53 Disable Redisgraph deployment in upstream
  Dockerfile
  cicd-scripts/run-e2e-tests.sh
  controllers/searchoperator_controller.go
  controllers/searchoperator_controller_test.go
Labels: approved, do-not-merge/hold, lgtm

#54 Update OWNERS and base docker image
  COMPONENT_VERSION
  Dockerfile
  Dockerfile.prow
  OWNERS
Labels: approved, lgtm

#56 store previous state in search-operator
  api/v1alpha1/searchoperator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/search.open-cluster-management.io_searchoperators.yaml
  controllers/searchoperator_controller.go
  controllers/searchoperator_controller_test.go
Labels: approved, lgtm

#57 Restart collector pod when enabling redisgraph
  controllers/searchoperator_controller.go
  controllers/searchoperator_controller_test.go
Labels: approved, do-not-merge/hold

#58 Turn off DEPLOY_REDISGRAPH flag
  Dockerfile
Labels: approved, lgtm

#59 Revert "Turn off DEPLOY_REDISGRAPH flag"
  Dockerfile
Labels: approved, lgtm
